import fs from 'node:fs/promises';
const dir = new URL('./', import.meta.url);
const read = file => fs.readFile(new URL(file, dir), 'utf8');
const data = (await read('data.js')).replace('export const jobs =','const jobs =').replace('export const candidates =','const fixtures =');
const icons = (await read('icons.js')).replaceAll('export const ','const ');
const main = (await read('main.js')).replace(/^import .*;\r?\n/gm,'');
await fs.writeFile(new URL('bundle.js',dir),'/* Generated by build.mjs. */\n(()=>{\n'+data+'\n'+icons+'\n'+main+'\n'+await read('agent.js')+'\n})();\n');
